### ISSUE TITLE
Check add worked

### ISSUE THREAD

**Issue by jjaffeux** [udan11/discourse-fingerprint#7]
Here you are not checking add worked, so your size could be 0 not because remove worked, but because add didn’t:

https://github.com/udan11/discourse-fingerprint/blob/2b960a8a73e623ef4bedf961aa4a05cdedf42b65/spec/fingerprint_spec.rb#L61

**Comment by udan11** [comment]
I did not bother to check because there is already [another test](https://github.com/udan11/discourse-fingerprint/blob/2b960a8a73e623ef4bedf961aa4a05cdedf42b65/spec/fingerprint_spec.rb#L10) checking that already.

Anyway, you can never be too careful. I will fix it.
